config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  namespace :public do
    root to: 'homes#top'
    get 'homes/about', as: 'about'
    resources :customers, only: [:show, :edit, :update]
    # 退会確認画面
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :items, only: [:show, :index]
    resources :cart_items, only: [:index, :create, :destroy, :update] do
      delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    end
    resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]
    get "/orders/thanks" => "orders#thanks"
    post "/orders/confirm" => "orders#confirm"
    resources :orders, only: [:index, :new, :create, :show]
    resources :genres, only: [:show]
  end

  namespace :admin do
    resources :items, only: [:show, :index, :new, :edit, :create, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get 'homes/top' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  validates :amount, numericality: { only_integer: true, greater_than: 0, less_than: 1000 }

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :cart_items, dependent: :destroy
   has_many :shipping_address, dependent: :destroy
   has_many :orders, dependent: :destroy

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name1
    self.last_name + self.first_name
  end

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
        (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :items, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}

  belongs_to :order
  belongs_to :item

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

  def shipping_address_display
  '〒' + shipping_postal_code + ' ' + shipping_address + ' ' + shipping_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def show
    @customer = Customer.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def edit
    @customer = Customer.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre .save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @params = params[:id]
    @order = Order.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def create
    @item = Item.new(item_params)
    @items = Item.all
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def edit
    @item = Item.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  def new
    @item = Item.new
    @genres = Genre.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-9 px-0 mt-3">
      <h4 class="m-3"><%= @customer.full_name1 %>さんの会員情報編集</h4>

<%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
  <table class="table table-borderless ml-5">
        <tr>
          <th>会員ID</th>
          <th></th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>名前</th>
          <th>(姓)</th>
          <th class="field">
            <%= f.text_field :last_name %>
            <%= f.label "(名)", class: "ml-5" %>
            <%= f.text_field :first_name, class: "ml-3" %>
          </th>
        </tr>
        <tr>
          <th>フリガナ</th>
          <th>(セイ)</th>
          <th class="field">
            <%= f.text_field :last_name_kana %>
            <%= f.label "(メイ)", class: "ml-5" %>
            <%= f.text_field :first_name_kana %>
          </th>
        </tr>
        <tr>
          <th>郵便番号</th>
          <th></th>
          <th class="field">
            <%= f.text_field :postal_code %>
          </th>
        </tr>
        <tr>
          <th>住所</th>
          <th></th>
          <th class="field">
            <%= f.text_field :address, size: 60 %>
          </th>
        </tr>
        <tr>
          <th>電話番号</th>
          <th></th>
          <th class="field">
            <%= f.text_field :telephone_number %>
          </th>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <th></th>
          <th class="field">
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </th>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <th></th>
          <th class="is_active">
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, '有効', value: true, class: "mr-5" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, '退会', value: false %>
          </th>
        </tr>
        <tr>
          <th></th>
          <th></th>
          <th class="form-group col-4 mx-auto">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
          </th>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 px-0 mx-auto">
    <h4>会員一覧</h4>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td>
                <%= customer.id %>
              </td>
              <td><%= link_to customer.full_name1, admin_customer_path(customer.id) %></td>
              <td><%= customer.email %></td>
              <td><% if customer.is_deleted == false %>
                    <p class="text-success font-weight-bold">有効</p>
                  <% else %>
                    <p class="text-danger font-weight-bold">退会</p>
                  <% end %>
              <td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-8 px-0 mx-auto">
      <h4 class="my-3"><%= @customer.full_name1 %>さんの会員詳細</h4>
      <table class="table table-borderless">
        <tr>
          <th>会員ID</th><td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
	        <td><%= @customer.full_name %></td>
        </tr>
        <tr>
	        <th>カナ</th>
	        <td><%= @customer.full_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted == false  %>
              <p class="text-success font-weight-bold">有効</p>
            <% else %>
              <p class="text-secondary font-weight-bold">退会</p>
            <% end %>
          <td>
        </tr>
      </table>
      <div class="col-4 mx-auto">
        <%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success m-2" %>
      </div>
    </div>
  </div>
</div>