config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  namespace :public do
    root to: 'homes#top'
    get 'homes/about', as: 'about'
    resources :customers, only: [:show, :edit, :update]
    # 退会確認画面
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :items, only: [:show, :index]
    resources :cart_items, only: [:index, :create, :destroy, :update] do
      delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    end
    resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]
    get "/orders/thanks" => "orders#thanks"
    post "/orders/confirm" => "orders#confirm"
    resources :orders, only: [:index, :new, :create, :show]
    resources :genres, only: [:show]
  end

  namespace :admin do
    resources :items, only: [:show, :index, :new, :edit, :create, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get 'homes/top' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  validates :amount, numericality: { only_integer: true, greater_than: 0, less_than: 1000 }

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :cart_items, dependent: :destroy
   has_many :shipping_address, dependent: :destroy
   has_many :orders, dependent: :destroy

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name1
    self.last_name + self.first_name
  end

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
        (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :items, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}

  belongs_to :order
  belongs_to :item

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

  def shipping_address_display
  '〒' + shipping_postal_code + ' ' + shipping_address + ' ' + shipping_name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre .save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @params = params[:id]
    @order = Order.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def create
    @item = Item.new(item_params)
    @items = Item.all
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def edit
    @item = Item.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  def new
    @item = Item.new
    @genres = Genre.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

    def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_status_params)
      if @order.order_status == "入金待ち"
        @order_details.update_all(making_status: "着手不可")
      elsif @order.order_status == "入金確認"
        @order_details.update_all(making_status: "製作待ち")
      end
      redirect_to request.referer
    else
      render admin_order_path(@order)
    end
  end

private

  def order_status_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <h4 class="m-3">ジャンル編集</h4>
      <%= form_with model:@genre, url: admin_genre_path, local:true do |f| %>
        <p class="my-5 mx-2">ジャンル名
          <%= f.text_field :name, class: "mx-2" %>
          <%= f.submit '変更を保存', class: "btn btn-success mx-2" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <h4 class="m-3">ジャンル一覧・追加</h4>
      <%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
      <p class="my-5 mx-2">ジャンル名
          <%= f.text_field :name, class: "mx-2" %>
          <%= f.submit '新規登録', class: "btn btn-success mx-2" %>
        </p>
      <% end %>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td>
                <%= genre.name %>
              </td>
              <td>
                <%= link_to "編集する", edit_admin_genre_path(genre.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 col-5 px-0 mx-auto">
      <h2>商品編集</h2>
      <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
        <div class="form-group">
          <label for="item_image">商品画像
          <%= f.file_field :image, accept: "image/*", class: "form-control-file item_image" %>
        </div>
        <div class="form-group">
          <label for="item_name">商品名</label>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <label for="item_introduction">商品説明</label>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <label for="item_name">ジャンル</label>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
        </div>
        <div class="form-group">
          <label for="item_price">税抜き価格</label>
          <%= f.text_field :price, type: "number", class: "form-control price" %>
        </div>
        <div class="form-group">
          <label for="item_is_active">販売ステータス</label>
          <div class="is_active">
            <div>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, '販売中', value: true, class: "mr-5" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, '販売停止中', value: false %>
            </div>
          </div>
        </div>
        <div class="form-group col-4 mx-auto">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 px-0 mx-auto">
      <div class="d-flex bd-highlight mb-3">
        <h4>商品一覧</h4>
        <%= link_to new_admin_item_path, class: 'ml-auto' do %>
          <button type="button" class="btn btn-primary rounded-circle p-0 ml-auto font-weight-bold" style="width:2rem;height:2rem;">＋</button>
        <% end %>
      </div>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td>
                <%= item.id %>
              </td>
              <td>
                <%= link_to item.name, admin_item_path(item.id) %>
              </td>
              <td>
                <%= item.price %>
              </td>
              <td>
                <%= item.genre.name %>
              </td>
              <td><% if item.is_active == true %>
                    <p class="text-success font-weight-bold">販売中</p>
                  <% else %>
                    <p class="text-danger font-weight-bold">販売停止中</p>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-9 px-0 mt-3">
      <h4 class="m-3">商品新規登録</h4>
      <%= form_with model:@item, url: admin_items_path, local:true do |f| %>
      <table class="table table-borderless ml-5">
      <tr>
        <th>商品画像</th>
        <th class="field">
        <%= f.file_field :image, class: "form-control-file image", accept: 'image/*' %>
        </th>
      </tr>
      <tr>
        <th>商品名</th>
        <th><%= f.text_field :name, class: "form-control name" %></th>
      </tr>
      <tr>
        <th>商品説明</th>
        <th><%= f.text_area :introduction, class: "form-control introduction" %></th>
      </tr>
      <tr>
        <th>ジャンル</th>
        <th><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></th>
      </tr>
      <tr>
        <th>税抜価格</th>
        <th><%= f.text_field :price, class: "form-control price" %>円</th>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <th>
          <%= f.radio_button :is_active, true, checked: true %>
          <%= f.label :is_active, "販売中" %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, "販売停止中" %>
        </th>
      </tr>
    </table>
    <div class="text-right">
      <%= f.submit "新規登録", class: 'btn btn-success' %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 px-0">
      <h4 class="text-center">商品詳細</h4>
      <%= image_tag @item.image.variant( resize: "250" ) %>
    </div>
    <div class="col-6 px-0 mt-5 mx-auto">
      <table class="table table-borderless">
        <tr>
          <th>商品名</th><td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th><td><%= safe_join(@item.introduction.split("\n"),tag(:br)) %></td>
        </tr>
        <tr>
          <th>ジャンル</th><td><%= @item.genre.name %></td>
        </tr>
        <tr valign="middle">
          <th>税込価格</br>(税抜価格)</th>
          <td><%= @item.add_tax_price.to_s(:dalimited) %>(<%= @item.price.to_s(:dalimited) %>)円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_active %>
              <p class="text-success font-weight-bold">販売中</p>
            <% else %>
              <p class="text-danger font-weight-bold">販売停止中</p>
            <% end %>
          <td>
        </tr>
      </table>
      <div class="col-4 mx-auto">
        <%= link_to '編集する', edit_admin_item_path(@item.id), class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 px-0">
      <div class="ml-3">
        <h4>注文履歴詳細</h4>
      </div>
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer.id) do %>
              <%= @order.customer.full_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= "〒#{@order.postal_code} #{@order.address} #{@order.name}" %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
          <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
            <%= f.select :order_status,Order.order_statuses.keys %>
            <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-9 px-0">
      <table class="table border">
        <tr>
          <th class="table-active">商品名</th>
          <th class="table-active">単価(税込)</th>
          <th class="table-active">数量</th>
          <th class="table-active">小計</th>
          <th class="table-active">製作ステータス</th>
        </tr>
      <% @order.order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.item.add_tax_price.to_s(:delimited) %></td>
          <td><%= order_detail.amount %></td>
          <td><%= (amount = (order_detail.item.add_tax_price * order_detail.amount)).to_s(:delimited) %></td>
          <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch, local: true do |f| %>
              <%= f.hidden_field :order_detail_id, :value => order_detail.id %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys %>
              <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="col-2 px-0 mt-auto ml-3">
    <table class="table table-borderless text-nowrap">
      <tr><th>送料</th><td>800</td></tr>
      <tr><th>商品合計</th><td><%= @order.total_payment - 800 %></td></tr>
      <tr><th>請求合計</th><td><%= @order.total_payment %></td></tr>
    </table>
    </br>
    </div>
  </div>
</div>