config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  namespace :public do
    root to: 'homes#top'
    get 'homes/about', as: 'about'
    resources :customers, only: [:show, :edit, :update]
    # 退会確認画面
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :items, only: [:show, :index]
    resources :cart_items, only: [:index, :create, :destroy, :update] do
      delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    end
    resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]
    get "/orders/thanks" => "orders#thanks"
    post "/orders/confirm" => "orders#confirm"
    resources :orders, only: [:index, :new, :create, :show]
    resources :genres, only: [:show]
  end

  namespace :admin do
    resources :items, only: [:show, :index, :new, :edit, :create, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get 'homes/top' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  validates :amount, numericality: { only_integer: true, greater_than: 0, less_than: 1000 }

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :cart_items, dependent: :destroy
   has_many :shipping_address, dependent: :destroy
   has_many :orders, dependent: :destroy

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name1
    self.last_name + self.first_name
  end

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
        (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :items, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}

  belongs_to :order
  belongs_to :item

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

  def shipping_address_display
  '〒' + shipping_postal_code + ' ' + shipping_address + ' ' + shipping_name
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @params = params[:id]
    @order = Order.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def create
    @item = Item.new(item_params)
    @items = Item.all
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def edit
    @item = Item.find(params[:id])
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  def new
    @item = Item.new
    @genres = Genre.all
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagano</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#ffedcc;">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Nagano_cake</a>
          <% if customer_signed_in? %>
          <p class="text-center">ようこそ、<%= current_customer.last_name %>さん！</p>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
      <% if customer_signed_in? %>
        <li class="nav-item">
          <%= link_to 'マイページ', public_customer_path(current_customer.id), class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", public_items_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", public_cart_items_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link btn btn-outline-dark mx-2' do %>
            ログアウト
          <% end %>
        </li>
      <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "商品一覧", admin_items_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "会員一覧", admin_customers_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "注文履歴一覧", admin_homes_top_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "About", public_about_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", public_items_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_customer_registration_path, data: {"turbolinks" => false}, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path, class: 'nav-link btn btn-outline-dark mx-2' %>
        </li>
      <% end %>
       </ul>
          </div>
        </div>
      </nav>
      <ul class="navbar-nav text-right" style="background-color:#ffedcc;">
      <% if customer_signed_in? %>
      <li class="nav-item">
      <%= search_form_for @q, url: public_items_path  do |f| %>
        <%= f.search_field :name_cont, placeholder: "Search" %>
        <%= f.submit "検索" %>
      <% end %>
      </li>
      <% elsif admin_signed_in? %>
      <li class="nav-item">
          <%= search_form_for @q, url: admin_items_path  do |f| %>
            <%= f.search_field :name_cont, placeholder: "Search" %>
            <%= f.submit "検索" %>
          <% end %>
      </li>
      <% else %>
      <% end %>

      </ul>
    </header>
    <main class="mb-auto">
      <p id="notice"><%= notice %></p>
    <%= yield %>
    </main>
    <footer  class="fixed-bottom" style="height:50px; background-color: #ffedcc;">
    </footer>
  </body>
</html>